### ISSUE TITLE
Error when checking grades

### ISSUE THREAD

**Issue by Douile** [joe-herbert/canvas-cli#1]
Got this when running `canvas g`

```
line 423: 2.666666666666667: syntax error: invalid arithmetic operator (error token is ".666666666666667")
```

**Comment by joe-herbert** [comment]
Think [this commit](https://github.com/joe-herbert/canvas-cli/commit/57b75f2be5ee477f2c716a3420f3e890a422c26e) should fix this problem, let me know if not. Thanks Tom.

**Comment by Douile** [comment]
Yes this works now, ty
